apiVersion: networking.k8s.io/v1
# apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-staging
  labels:
    app: {{ .Values.name }}
spec:
  rules:
    - host:  {{ .Values.ingress.hosts.host }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
               name: {{ .Values.name }}
               port: 
                number: {{ .Values.service.port }}

  tls:
  - hosts:
    - {{ .Values.ingress.hosts.host }}
    secretName: {{ .Values.ingress.secret }}-secret
